# Image upload
kms_froala_editor_upload_image:
    path: /upload_image
    controller: KMS\FroalaEditorBundle\Controller\MediaController::uploadImage

kms_froala_editor_delete_image:
    path: /delete_image
    controller: KMS\FroalaEditorBundle\Controller\MediaController::deleteImage

kms_froala_editor_load_images:
    path: /load_images
    controller: KMS\FroalaEditorBundle\Controller\MediaController::loadImages

# File upload
kms_froala_editor_upload_file:
    path: /upload_file
    controller: KMS\FroalaEditorBundle\Controller\MediaController::uploadFile

# Video upload
kms_froala_editor_upload_video:
    path: /upload_video
    controller: KMS\FroalaEditorBundle\Controller\MediaController::uploadVideo
